version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
          - "ts-node"
      production-dependencies:
        patterns:
          - "axios"
          - "commander"
          - "dotenv"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
